apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../../infrastructure/controllers/dragonfly
configMapGenerator:
  - name: app-conf
    literals:
      - APP_STORE: "redis"
      - APP_REDIS_URL: "redis://dragonfly-dragonfly-redis-master.dragonfly.svc.cluster.local:6379"
