resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - dragonfly.yaml
configMapGenerator:
  - name: app-conf
    literals:
      - APP_STORE="redis"
      - APP_REDIS_URL="redis://dragonfly:6379"
