apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: course-app
spec:
  selector:
    app: course-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

