apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app
spec:
  replicas: 1
#  template:
#    spec:
#      containers:
#        - name: course-app
#          envFrom:
#            - configMapRef:
#                name: app-conf
